@rootURL = http://localhost:5286
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5IiwiZW1haWwiOiJzYWJiaXIwMTNAb3V0bG9vay5jb20iLCJyb2xlIjoiTGFuZGxvcmQiLCJuYmYiOjE3NTE2OTQ3NzEsImV4cCI6MTc1MTcwNTU3MSwiaWF0IjoxNzUxNjk0NzcxLCJpc3MiOiJodHRwczovL2hvdXNlcmVudHN5c3RlbS5jb20iLCJhdWQiOiJodHRwczovL2hvdXNlcmVudHN5c3RlbS5jb20ifQ.t4QQdbztOjqPDyxTM3uWo5A8FTCXh2j-VbBwwRgLZXQ

GET {{rootURL}}/weatherforecast/
Accept: application/json

//start user
###
POST {{rootURL}}/api/user/register
Content-Type: application/json
{
  "fullName": "Sabbir Ahmed",
  "email": "sabbir014@gmail.com",
  "password": "P@ssw0rd123",
  "phoneNumber": "+8801738034915",
  "nid": "1234567890123",
  "role": "Tenant"
}

###
POST {{rootURL}}/api/user/register
Content-Type: application/json
{
  "fullName": "Sabbir Chowdhury",
  "email": "sabbir013@outlook.com",
  "password": "P@ssw0rd123",
  "phoneNumber": "+8801738034915",
  "nid": "12345678901236",
  "role": "Landlord"
}

###
POST {{rootURL}}/api/user/login
Content-Type: application/json
{
  "email": "sabbir014@gmail.com",
  "password": "P@ssw0rd1234"
}

###
POST {{rootURL}}/api/user/login
Content-Type: application/json
{
  "email": "sabbirahmedchowdhury013@gmail.com",
  "password": "P@ssw0rd123"
}

###
GET {{rootURL}}/api/user/profile
Authorization: Bearer {{token}}
Accept: application/json

###
PUT {{rootURL}}/api/user/profile
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "fullName": "Sabbir Ahmed Chowdhury",
  "phoneNumber": "+8801738034915",
  "currentPassword": "P@ssw0rd1234",
  "newPassword": "P@ssw0rd1234",
  "isNIDVerified": true
}

###

//end user

//start property
###
POST {{rootURL}}/api/property
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "address": "120/b, Notun Rasta, Maniknagar, Mugda",
  "city": "Dhaka",
  "rentAmount": 25000,
  "bedrooms": 3,
  "bathrooms": 3
}
###
GET {{rootURL}}/api/property
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/property/2
Authorization: Bearer {{token}}
###
PUT {{rootURL}}/api/property/2
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "address": "Rankin Street",
  "city": "Dhaka",
  "rentAmount": 28000,
  "securityDeposit": 30000,
  "bedrooms": 4,
  "bathrooms": 3,
  "amenities": "no amenities",
  "description": "ha ha",
  "isAvailable": true
}
###
Delete {{rootURL}}/api/property/4
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/property/search?city=Dhaka&minRent=10000&maxRent=20000&page=1&pageSize=5
Authorization: Bearer {{token}}
###
POST {{rootURL}}/api/property/1/images
Authorization: Bearer {{token}}
Content-Type: multipart/form-data
###
//end property

//start lease
###
POST {{rootURL}}/api/Lease
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "startDate": "2025-07-04T16:44:38.485Z",
  "endDate": "2026-07-04T16:44:38.485Z",
  "monthlyRent": 15000,
  "termsAndConditions": "abc",
  "propertyId": 6,
  "tenantId": 3
}
###
GET {{rootURL}}/api/Lease/2
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/Lease/tenant/3
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/lease/property/1
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/Lease/2/document
Authorization: Bearer {{token}}
###
//end lease

//start maintenance
POST {{rootURL}}/api/maintenance
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "description": "fix window2",
  "propertyId": 6,
  "tenantId": 3
}
###
PUT {{rootURL}}/api/maintenance/2/status
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "status": 2
}
###
PUT {{rootURL}}/api/maintenance/2/status
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "workerId": 1
}
###
GET {{rootURL}}/api/maintenance/2
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/maintenance/tenant/3
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/maintenance/property/1
Authorization: Bearer {{token}}
###
//end maintenance

//start payment
POST {{rootURL}}/api/payments
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "leaseId": 1,
  "amount": 15000,
  "dueDate": "2025-07-05T23:40:19.947Z"
}
###
PUT {{rootURL}}/api/payments/2/status
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "status": 0
}
###
POST {{rootURL}}/api/payments/1/verify
Authorization: Bearer {{token}}
Content-Type: application/json
###
GET {{rootURL}}/api/payments/1
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/payments/lease/1
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/payments/overdue
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/payments/tenant/3/history
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/payments/1/late-fee
Authorization: Bearer {{token}}
###
GET {{rootURL}}/api/payments/due/"2025-07-05T23:40:19.947Z"
Authorization: Bearer {{token}}
###
POST {{rootURL}}/api/payments/1/slip
Authorization: Bearer {{token}}
Content-Type: multipart/form-data
###
//end payment